# Append specific configuration to the C source build (here log=info)
# The UUID for the Trusted Application
BINARY=9407a4d1-33a0-4b9b-a568-f184ddf8b65c

# Source the TA-devkit make file
include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk

