BINARY = 7e1a5d1e-c3bc-4556-8489-3e15398ce932

CFG_TEE_TA_LOG_LEVEL ?= 4

TA_DEV_KIT_DIR = /home/harasha/myboot/secure_manager/optee_os/out/arm-plat-stm32mp1/export-ta_arm32

include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk
